minecraft_version=26.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
fabric_api_version=0.159.0+26.2
mod_version=2.3

maven_group=io.github.thepro1604
archives_base_name=AdvancedChatBox
malilib_version=26.2-0.29.5
advancedchat_version=2.3
mxparser_version=4.4.2
org.gradle.jvmargs=-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configuration-cache=false

modrinth_slug=advancedchatbox-next

# default_release_type can be stable, beta, or alpha
default_release_type=stable
project_name=AdvancedChatBox
project_url=https://modrinth.com/mod/advancedchatbox-next
project_logo=https://raw.githubusercontent.com/thepro1604/AdvancedChatBox/main/src/main/resources/assets/advancedchatbox/icon.png
project_color=0x4480ad
changelog_hide_unimportant_commits=true
changelog_max_commit_search=200
discord_webhook_changelog_line_limit=10
